rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('add_category/', views.add_category, name="add_category"),
    path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),
    path('category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('restricted/', views.restricted, name='restricted'),
    path('logout/', views.user_logout, name='logout'),
]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from rango import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
import re

from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


def unique_slugify(instance, value, slug_field_name='slug', queryset=None,
                   slug_separator='-'):
    """
    Calculates and stores a unique slug of ``value`` for an instance.

    ``slug_field_name`` should be a string matching the name of the field to
    store the slug in (and the field to check against for uniqueness).

    ``queryset`` usually doesn't need to be explicitly provided - it'll default
    to using the ``.all()`` queryset from the model's default manager.
    """
    slug_field = instance._meta.get_field(slug_field_name)

    slug = getattr(instance, slug_field.attname)
    slug_len = slug_field.max_length

    # Sort out the initial slug, limiting its length if necessary.
    slug = slugify(value)
    if slug_len:
        slug = slug[:slug_len]
    slug = _slug_strip(slug, slug_separator)
    original_slug = slug

    # Create the queryset if one wasn't explicitly provided and exclude the
    # current instance from the queryset.
    if queryset is None:
        queryset = instance.__class__._default_manager.all()
    if instance.pk:
        queryset = queryset.exclude(pk=instance.pk)

    # Find a unique slug. If one matches, at '-2' to the end and try again
    # (then '-3', etc).
    next = 2
    while not slug or queryset.filter(**{slug_field_name: slug}):
        slug = original_slug
        end = '%s%s' % (slug_separator, next)
        if slug_len and len(slug) + len(end) > slug_len:
            slug = slug[:slug_len-len(end)]
            slug = _slug_strip(slug, slug_separator)
        slug = '%s%s' % (slug, end)
        next += 1

    setattr(instance, slug_field.attname, slug)


def _slug_strip(value, separator='-'):
    """
    Cleans up a slug by removing slug separator characters that occur at the
    beginning or end of a slug.

    If an alternate separator is used, it will also replace any instances of
    the default '-' separator with the new separator.
    """
    separator = separator or ''
    if separator == '-' or not separator:
        re_sep = '-'
    else:
        re_sep = '(?:-|%s)' % re.escape(separator)
    # Remove multiple instances and if an alternate separator is provided,
    # replace the default '-' separator.
    if separator != re_sep:
        value = re.sub('%s+' % re_sep, separator, value)
    # Remove separator from the beginning and end of the slug.
    if separator:
        if separator != '-':
            re_sep = re.escape(separator)
        value = re.sub(r'^%s+|%s+$' % (re_sep, re_sep), '', value)
    return value


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        unique_slugify(self, self.name)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.CharField(max_length=200)
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from django.contrib.auth.models import User
from rango.models import *
from url_normalize import url_normalize


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=Category._meta.get_field('name').max_length,
                           help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name', )


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=Page._meta.get_field('title').max_length,
                            help_text="Please enter the title of the page.")
    url = forms.CharField(max_length=Page._meta.get_field('url').max_length,
                         help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ('category', )

    def clean(self):
        cleaned_data = self.cleaned_data
        cleaned_data['url'] = url_normalize(cleaned_data.get('url'), default_scheme='http')
        return cleaned_data


class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

rango/views.py
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.urls import reverse
from rango.models import *
from rango.forms import *


def index(request):
    # top 5 categories (in likes)
    most_liked_categories = Category.objects.order_by('-likes')[:5]
    most_viewed_pages = Page.objects.order_by('-views')[:5]
    visitor_cookie_handler(request)
    context_dict = {
        'boldmessage': 'Crunchy, creamy, cookie, candy, cupcake!',
        'categories': most_liked_categories,
        'pages': most_viewed_pages,
    }
    response = render(request, 'rango/index.html', context=context_dict)
    return response


def about(request):
    visitor_cookie_handler(request)
    visits = get_server_side_cookie(request, 'visits')
    response = render(request, 'rango/about.html', context={'visits': visits})
    return response


def show_category(request, category_name_slug):
    try:
        # can we find a category name with the given slug?
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)
        context_dict = {'pages': pages, 'category': category}
    except Category.DoesNotExist:
        context_dict = {'category': None, 'pages': None}

    return render(request, 'rango/category.html', context=context_dict)


@login_required
def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)

        # Have we been provided with a valid form?
        if form.is_valid():
            # Save the new category to the database
            form.save(commit=True)
            return redirect(reverse('rango:index'))
        else:
            # The supplied form has errors.
            print(form.errors)

    # Will handle the bad form, new form, or no form supplied cases
    return render(request, 'rango/add_category.html', {'form': form})


@login_required
def add_page(request, category_name_slug):
    form = PageForm()
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        return redirect(reverse('rango:index'))

    if request.method == 'POST':
        form = PageForm(request.POST)

        # Have we been provided with a valid form?
        if form.is_valid():
            # Save the new category to the database
            page = form.save(commit=False)
            page.category = category
            page.save()
            return redirect(reverse('rango:show_category', kwargs={'category_name_slug': category_name_slug}))
        else:
            # The supplied form has errors.
            print(form.errors)

    # Will handle the bad form, new form, or no form supplied cases
    return render(request, 'rango/add_page.html', {'category': category, 'form': form})


def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    context = {'user_form': user_form, 'profile_form': profile_form, 'registered': registered }
    return render(request, 'rango/register.html', context=context)


def user_login(request):
    print('in login view')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                print('bang')
                login(request, user)
                print('bang bang')
                return redirect(reverse('rango:index'))
            else:
                return HttpResponse("Your Rango account is disabled")
        else:
            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")
    else:
        print('posting')
        return render(request, 'rango/login.html')


@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('rango:index'))


@login_required
def restricted(request):
    return render(request, 'rango/restricted.html')


def get_server_side_cookie(request, cookie, default_value=None):
    val = request.session.get(cookie)
    if not val:
        val = default_value
    return val


def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).days > 0:
        visits += 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie

    request.session['visits'] = visits

rango/templates/rango/about.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
About Rango
{% endblock %}

{% block body_block %}
Here is the about page. <br />
<strong>This tutorial has been put together by &lt;your-name&gt;</strong><br />
<div>
    <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" /><br />
    <img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of a Cat" />
</div>
<div>
    Visits: {{ visits }}
</div>
{% endblock %}

rango/templates/rango/add_category.html
{% extends 'rango/base.html' %}

{% block title_block %}
    Add a Category
{% endblock %}

{% block body_block %}
<form id="category_form" method="post" action="{% url 'rango:add_category' %}">
    {% csrf_token %}
    {% for h in form.hidden_fields %}
        {{ h }}
    {% endfor %}
    {% for f in form.visible_fields %}
        {{ f.errors }}
        {{ f.help_text }}
        {{ f }}
    {% endfor %}
    <input type="submit" name="submit" value="Create Category" />
</form>
{% endblock %}

rango/templates/rango/add_page.html
{% extends 'rango/base.html' %}

{% block title_block %}
Add a Page
{% endblock %}

{% block body_block %}
<form id="page_form" method="post" action="{% url 'rango:add_page' category.slug %}">
    {% csrf_token %}
    {% for h in form.hidden_fields %}
        {{ h }}
    {% endfor %}
    {% for f in form.visible_fields %}
        {{ f.errors }}
        {{ f.help_text }}
        {{ f }} <br />
    {% endfor %}
    <input type="submit" name="submit" value="Create Page" />
</form>
{% endblock %}

rango/templates/rango/base.html
<!DOCTYPE html>
{% load static %}
{% load rango_template_tags %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Rango -
    {% block title_block %}
        How to Tango with Django!
    {% endblock %}
    </title>
</head>
<body>
    <div>
        {% block body_block %}
        {% endblock %}
    </div>
    <div>
        {% block sidebar_block %}
        {% get_category_list category %}
        {% endblock %}
    </div>
    <hr />
    <div>
        <ul>
            {% if user.is_authenticated %}
                <li><a href="{% url 'rango:restricted' %}">Restricted</a></li>
                <li><a href="{% url 'rango:logout' %}">Logout</a></li>
                <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
            {% else %}
                <li><a href="{% url 'rango:register' %}">Sign Up</a></li>
                <li><a href="{% url 'rango:login' %}">Login</a></li>
            {% endif %}
            <li><a href="{% url 'rango:about' %}">About</a></li>
            <li><a href="{% url 'rango:index' %}">Index</a></li>
        </ul>
    </div>
</body>
</html>

rango/templates/rango/categories.html
<ul>
    {% if categories %}
        {% for c in categories %}
            <li>
            {% if c == current_category %}
            <strong>
            {% endif %}
            <a href="{% url 'rango:show_category' c.slug %}">{{ c }}</a>
            {% if c == current_category %}
            </strong>
            {% endif %}
            </li>
        {% endfor %}
    {% else %}
        <li><strong>There are no categories present</strong></li>
    {% endif %}
</ul>

rango/templates/rango/category.html
{% extends 'rango/base.html' %}

{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}

{% block body_block %}
    {% if category %}
        <h1>{{ category }}</h1>
        {% if pages %}
        <ul>
            {% for p in pages %}
                <li><a href="{{ p.url }}">{{ p }}</a></li>
            {% endfor %}
        </ul>
        {% else %}
            <strong>No pages currently in category.</strong>
        {% endif %}
        {% if user.is_authenticated %}
        <a href="{% url 'rango:add_page' category.slug %}">Add Page</a><br />
        {% endif %}
    {% else %}
        The specified category does not exist.
    {% endif %}
{% endblock %}

rango/templates/rango/index.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
Homepage
{% endblock %}

{% block body_block %}
{% if user.is_authenticated %}
    howdy {{ user.username }}!
{% else %}
    hey there partner!
{% endif %}

<h2>Most Liked Categories</h2>
{% if categories %}
<ul>
    {% for c in categories %}
        <li><a href="{% url 'rango:show_category' c.slug %}">{{ c }}</a></li>
    {% endfor %}
</ul>
{% else %}
    <strong>There are no categories present.</strong>
{% endif %}

<h2>Most Viewed Pages</h2>
{% if pages %}
<ul>
    {% for p in pages %}
        <li><a href="{{ p.url }}">{{ p }}</a></li>
    {% endfor %}
</ul>
{% else %}
    <strong>There are no pages present.</strong>
{% endif %}

<div>
<img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
</div>
{% endblock %}

rango/templates/rango/login.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
    <h1>Login to Rango</h1>
    <form id="login_form" method="post" action="{% url 'rango:login' %}">
        {% csrf_token %}
        Username: <input type="text" name="username" value="" size="50" /><br />
        Password: <input type="password" name="password" value="" size="50" /><br />
        <input type="submit" value="submit" />
    </form>
{% endblock %}

rango/templates/rango/register.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
Register
{% endblock %}

{% block body_block %}
<h1>Register for Rango</h1>
{% if registered %}
Rango says: <strong>thank you for registering!</strong>
<a href="{% url 'rango:index' %}">Return to the homepage.</a><br />
{% else %}
    Rango says: <strong>register here!</strong><br />
    <form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name="submit" value="Register" />
    </form>
{% endif %}
{% endblock %}

rango/templates/rango/restricted.html
{% extends 'rango/base.html' %}

{% block title_block %}
Restricted Page
{% endblock %}

{% block body_block %}
Since you're logged in, you can see this text!
{% endblock %}